"""install_prod_cli.sh — the `jarvis` a human types, and INV-PROD-CLI which watches it.

Issue 757. Every piece of production's identity — `JARVIS_HOME`, `PRODUCTION_CODE`,
`JARVIS_ENV` — lived only in the two systemd units, so it reached the daemon and its
workers and reached nothing a human types. `jarvis` was command-not-found, and the
obvious fallback (the deployed venv's binary by full path) ran production CODE against
`~/.jarvis`, the DEV instance's state, silently and while the dashboard badge said
`production`.

The wrapper is the fix and the three exports are the whole reason it is a wrapper rather
than a symlink. The script is driven for real against tmp_path, and the invariant is
tested beside it the way `INV-SERVICE-PATH` sits in test_install_prod_service.py.
"""

from __future__ import annotations

import os
import stat
import subprocess
from pathlib import Path

import pytest

REPO_ROOT = Path(__file__).resolve().parents[1]
SCRIPT = REPO_ROOT / "scripts" / "install_prod_cli.sh"
SERVICE_SCRIPT = REPO_ROOT / "scripts" / "install_prod_service.sh"

BASE_PATH = "/usr/local/bin:/usr/bin:/bin"

#: The marker comment that tells our wrapper from any other `jarvis` on PATH.
MARKER = "generated by scripts/install_prod_cli.sh"


@pytest.fixture()
def prod(tmp_path: Path) -> Path:
    """A production root deployed enough for the script's precondition to pass."""
    venv_bin = tmp_path / "prod" / "jarvis_os" / ".venv" / "bin"
    venv_bin.mkdir(parents=True)
    jarvis = venv_bin / "jarvis"
    jarvis.write_text("#!/bin/sh\nexit 0\n")
    jarvis.chmod(jarvis.stat().st_mode | stat.S_IEXEC)
    return tmp_path / "prod"


def _run(prod_root: Path, tmp_path: Path, *, path: str = BASE_PATH,
         bin_dir: Path | None = None,
         args: list[str] | None = None) -> subprocess.CompletedProcess[str]:
    bin_dir = bin_dir if bin_dir is not None else tmp_path / "bin"
    env = {"PATH": path, "HOME": str(tmp_path / "home"),
           "PRODUCTION_CODE": str(prod_root), "USER": os.environ.get("USER", "t")}
    return subprocess.run(
        ["bash", str(SCRIPT), "--bin-dir", str(bin_dir), *(args or [])],
        capture_output=True, text=True, env=env, check=False)


def _exports(text: str) -> dict[str, str]:
    """The `export NAME="value"` lines of a rendered wrapper."""
    found = {}
    for line in text.splitlines():
        line = line.strip()
        if line.startswith("export "):
            name, _, value = line[len("export "):].partition("=")
            found[name] = value.strip().strip('"')
    return found


def _unit_environment(unit: Path) -> dict[str, str]:
    found = {}
    for line in unit.read_text().splitlines():
        line = line.strip()
        if line.startswith("Environment="):
            name, _, value = line[len("Environment="):].partition("=")
            found[name] = value.strip().strip('"')
    return found


# -- the wrapper ----------------------------------------------------------------


def test_it_renders_an_executable_wrapper_that_execs_the_deployed_venv(prod, tmp_path):
    result = _run(prod, tmp_path)
    wrapper = tmp_path / "bin" / "jarvis"

    assert result.returncode == 0, result.stderr
    assert f"installed {wrapper}" in result.stdout
    assert stat.S_IMODE(wrapper.stat().st_mode) == 0o755
    assert (f'exec "{prod}/jarvis_os/.venv/bin/jarvis" "$@"'
            in wrapper.read_text().splitlines()[-1])


def test_the_exports_are_the_units_environment_values(prod, tmp_path):
    """The contract of the whole feature: a command typed in a shell and a command the
    daemon runs must reach ONE fleet. Drift between these two files is the only way this
    breaks quietly, so the two renderers are compared rather than the text asserted."""
    _run(prod, tmp_path)
    units = tmp_path / "units"
    svc = subprocess.run(
        ["bash", str(SERVICE_SCRIPT), "--dry-run", "--unit-dir", str(units)],
        capture_output=True, text=True, check=False,
        env={"PATH": BASE_PATH, "HOME": str(tmp_path / "home"),
             "PRODUCTION_CODE": str(prod), "USER": os.environ.get("USER", "t")})
    assert svc.returncode == 0, svc.stderr

    wrapper = _exports((tmp_path / "bin" / "jarvis").read_text())
    unit = _unit_environment(units / "jarvis.service")

    for name in ("JARVIS_HOME", "PRODUCTION_CODE", "JARVIS_ENV"):
        assert wrapper[name] == unit[name], name
    assert wrapper["JARVIS_HOME"] == f"{prod}/state"
    assert wrapper["JARVIS_ENV"] == "production"


def test_it_refuses_when_production_is_not_deployed(tmp_path):
    """A wrapper that execs a missing file is a `jarvis` reporting `No such file or
    directory` — worse than `command not found`."""
    result = _run(tmp_path / "empty", tmp_path)

    assert result.returncode != 0
    assert "not deployed yet" in result.stderr
    assert not (tmp_path / "bin" / "jarvis").exists()


def test_dry_run_prints_the_plan_and_writes_nothing(prod, tmp_path):
    result = _run(prod, tmp_path, args=["--dry-run"])

    assert result.returncode == 0, result.stderr
    assert str(tmp_path / "bin" / "jarvis") in result.stdout
    assert MARKER in result.stdout, "the rendered body is part of the plan"
    assert not (tmp_path / "bin").exists()
    assert not (tmp_path / "home").exists(), "wrote outside --bin-dir"


def test_it_is_idempotent(prod, tmp_path):
    first = _run(prod, tmp_path)
    before = (tmp_path / "bin" / "jarvis").read_bytes()
    second = _run(prod, tmp_path)

    assert (first.returncode, second.returncode) == (0, 0)
    assert (tmp_path / "bin" / "jarvis").read_bytes() == before


def test_it_says_so_when_the_bin_dir_is_not_on_the_callers_path(prod, tmp_path):
    """Same reasoning as the `gh`-reachability note in install_prod_service.sh: the
    install succeeds either way and the only symptom is a feature that never happens."""
    bin_dir = tmp_path / "bin"

    off = _run(prod, tmp_path, bin_dir=bin_dir)
    on = _run(prod, tmp_path, bin_dir=bin_dir, path=f"{bin_dir}:{BASE_PATH}")

    assert str(bin_dir) in off.stderr
    assert "PATH" in off.stderr
    assert str(bin_dir) not in on.stderr


def test_the_rendered_wrapper_is_valid_bash_and_forwards_argv(prod, tmp_path):
    """`"$@"` not `$*`: an argument containing a space must arrive as one argument."""
    _run(prod, tmp_path)
    wrapper = tmp_path / "bin" / "jarvis"
    stub = prod / "jarvis_os" / ".venv" / "bin" / "jarvis"
    out = tmp_path / "seen.txt"
    stub.write_text(
        "#!/bin/sh\n"
        f'printf "%s\\n" "$JARVIS_HOME" "$PRODUCTION_CODE" "$JARVIS_ENV" "$#" "$@" > {out}\n')

    syntax = subprocess.run(["bash", "-n", str(wrapper)], capture_output=True, text=True)
    assert syntax.returncode == 0, syntax.stderr

    run = subprocess.run([str(wrapper), "wo", "show", "two words"],
                         capture_output=True, text=True,
                         env={"PATH": BASE_PATH, "HOME": str(tmp_path / "home")})
    assert run.returncode == 0, run.stderr
    assert out.read_text().splitlines() == [
        f"{prod}/state", str(prod), "production", "3", "wo", "show", "two words"]


# -- INV-PROD-CLI ---------------------------------------------------------------
#
# The third member of the family that INV-SERVICE-PATH and INV-PROD-CLEAN started: a
# one-time manual install step that nothing ever re-ran or compared.


@pytest.fixture()
def deployed(prod: Path, tmp_path: Path, monkeypatch) -> Path:
    """A fake deployed production the invariant will accept as real, plus a bin dir."""
    (prod / "jarvis_os" / ".git").mkdir()
    from jarvis import paths, release
    monkeypatch.setenv(paths.PRODUCTION_ROOT_ENV, str(prod))
    monkeypatch.setenv(release.CLI_BIN_DIR_ENV, str(tmp_path / "bin"))
    return prod


def _violations():
    from jarvis import invariants
    return list(invariants.check_prod_cli())


def _wrapper(tmp_path: Path, body: str) -> Path:
    bin_dir = tmp_path / "bin"
    bin_dir.mkdir(parents=True, exist_ok=True)
    path = bin_dir / "jarvis"
    path.write_text(body)
    return path


def test_a_missing_wrapper_is_a_violation(deployed, tmp_path):
    found = _violations()

    assert [v.invariant for v in found] == ["INV-PROD-CLI"]
    assert "install_prod_cli.sh" in found[0].detail, "no way out is named"
    assert found[0].context["wrapper"] == str(tmp_path / "bin" / "jarvis")


def test_a_wrapper_the_real_script_rendered_is_silent(deployed, tmp_path):
    """Rendered, not hand-written: this is what closes the loop between the two halves."""
    result = _run(deployed, tmp_path)
    assert result.returncode == 0, result.stderr

    assert _violations() == []


def test_a_wrapper_pointing_at_another_checkout_is_a_violation(deployed, tmp_path):
    _run(deployed, tmp_path)
    wrapper = tmp_path / "bin" / "jarvis"
    wrapper.write_text(wrapper.read_text().replace(
        f'exec "{deployed}/jarvis_os/.venv/bin/jarvis"', 'exec "/other/.venv/bin/jarvis"'))

    found = _violations()

    assert [v.invariant for v in found] == ["INV-PROD-CLI"]
    assert found[0].context["target"] == "/other/.venv/bin/jarvis"
    assert found[0].context["expected_target"] == str(
        deployed / "jarvis_os" / ".venv" / "bin" / "jarvis")


def test_a_wrapper_exporting_another_home_is_a_violation(deployed, tmp_path):
    """Target correct, home wrong — which is the silent-wrong-fleet half of issue 757."""
    _run(deployed, tmp_path)
    wrapper = tmp_path / "bin" / "jarvis"
    wrapper.write_text(wrapper.read_text().replace(
        f'JARVIS_HOME="{deployed}/state"', 'JARVIS_HOME="/home/someone/.jarvis"'))

    found = _violations()

    assert [v.invariant for v in found] == ["INV-PROD-CLI"]
    assert found[0].context["jarvis_home"] == "/home/someone/.jarvis"
    assert found[0].context["expected_home"] == f"{deployed}/state"


def test_a_jarvis_on_path_that_is_not_ours_is_reported(deployed, tmp_path):
    """The defect's second half: most likely a dev install pointing at ~/.jarvis. The
    detail says it was not generated here, so a deliberate install can be read and kept."""
    _wrapper(tmp_path, "#!/bin/sh\nexec /usr/bin/true\n")

    found = _violations()

    assert [v.invariant for v in found] == ["INV-PROD-CLI"]
    assert found[0].context["generated"] is False


def test_no_production_deployment_is_silent(tmp_path, monkeypatch):
    """Every dev-only machine. Nothing to report and nothing a human there should do."""
    from jarvis import paths, release
    monkeypatch.setenv(paths.PRODUCTION_ROOT_ENV, str(tmp_path / "nowhere"))
    monkeypatch.setenv(release.CLI_BIN_DIR_ENV, str(tmp_path / "bin"))

    assert _violations() == []


def test_the_check_is_doctor_only():
    """The reconcile tick must not file an inbox item every few seconds about a file
    only a human can install."""
    from jarvis import invariants

    assert invariants.check_prod_cli in invariants.OS_INVARIANTS
    assert invariants.check_prod_cli not in invariants.INVARIANTS
