"""shipit release script — cuts a release from an ALREADY-merged main.

The correct process (mandated 2026-07-19): code lands on main via a reviewed PR;
shipit then cuts `release/jarvis-X.Y.Z` from main and does the version bump + tag
ON THE RELEASE BRANCH — main is never committed to. A Telegram notification fires
at the end. Version numbering derives from the latest `jarvis-*` tag (main's
pyproject is no longer bumped by shipit).

These drive the real scripts/shipit.sh in --dry-run against a throwaway repo, so
nothing is committed, deployed, or restarted.
"""

from __future__ import annotations

import os
import shutil
import stat
import subprocess
from pathlib import Path

import pytest

SHIPIT = Path(__file__).resolve().parents[1] / "scripts" / "shipit.sh"

#: Resolved once, by absolute path: the no-uv-on-PATH test hands the script a PATH too
#: small to find an interpreter.
BASH = shutil.which("bash") or "/bin/bash"


def _git(repo: Path, *args: str) -> None:
    subprocess.run(["git", "-C", str(repo), *args], check=True,
                   capture_output=True, text=True)


def _make_repo(tmp_path: Path) -> Path:
    """A dev clone whose `origin` is a bare remote — git is the source of truth."""
    repo = tmp_path / "dev"
    (repo / "scripts").mkdir(parents=True)
    shutil.copy(SHIPIT, repo / "scripts" / "shipit.sh")
    os.chmod(repo / "scripts" / "shipit.sh", 0o755)
    (repo / "pyproject.toml").write_text(
        '[project]\nname = "jarvis-os"\nversion = "0.1.1"\n')
    (repo / "README.md").write_text("# dev\n")
    # The artifacts the OS itself writes into a project it manages — tracked here so
    # tests can dirty them the way the live daemon does.
    (repo / "OPERATION.md").write_text("<!-- Generated by Jarvis OS (template v5). -->\n")
    (repo / "ASSUMPTIONS.md").write_text("# ASSUMPTIONS\n")
    (repo / ".claude").mkdir()
    (repo / ".claude" / "settings.json").write_text('{"_jarvis": {"managed": true}}\n')
    # Not written by the OS — rewritten by Serena on every project activation, which
    # makes it dirty just as reliably. Tracked here for the same reason as the rest.
    (repo / ".serena").mkdir()
    (repo / ".serena" / "project.yml").write_text("language: python\nignored_paths: []\n")
    _git(repo, "init", "-q", "-b", "main")
    _git(repo, "config", "user.email", "t@example.com")
    _git(repo, "config", "user.name", "Test")
    _git(repo, "add", "-A")
    _git(repo, "commit", "-q", "-m", "init")

    origin = tmp_path / "origin.git"
    subprocess.run(["git", "init", "-q", "--bare", "-b", "main", str(origin)],
                   check=True, capture_output=True, text=True)
    _git(repo, "remote", "add", "origin", str(origin))
    _git(repo, "push", "-q", "-u", "origin", "main")
    return repo


def _stub(directory: Path, name: str) -> Path:
    """A no-op stand-in for a tool the script only checks the presence of."""
    directory.mkdir(parents=True, exist_ok=True)
    p = directory / name
    p.write_text("#!/bin/sh\nexit 0\n")
    p.chmod(p.stat().st_mode | stat.S_IEXEC)
    return p


def _commit(repo: Path, subject: str) -> None:
    """One commit on the current branch — the shape a squash-merged PR leaves on main."""
    (repo / "notes.txt").write_text(subject + "\n")
    _git(repo, "add", "-A")
    _git(repo, "commit", "-q", "-m", subject)


def _tag_like_shipit(repo: Path, version: str) -> None:
    """Tag the way shipit itself does, because that shape is what the notes must handle.

    A release tag never sits on main: it is a lone `Release jarvis-X.Y.Z` bump commit on
    a release branch cut from main. The previous tag is therefore NOT an ancestor of the
    main head being shipped, so a changelog derived from it has to lean on reachability
    rather than on the tag lying in main's own line.
    """
    _git(repo, "checkout", "-q", "-b", f"release/jarvis-{version}")
    (repo / "pyproject.toml").write_text(
        f'[project]\nname = "jarvis-os"\nversion = "{version}"\n')
    _git(repo, "add", "-A")
    _git(repo, "commit", "-q", "-m", f"Release jarvis-{version}")
    _git(repo, "tag", "-a", f"jarvis-{version}", "-m", f"Jarvis OS {version}")
    _git(repo, "checkout", "-q", "main")


def _dry_run(repo: Path, prod: Path, *args: str) -> subprocess.CompletedProcess[str]:
    """Drive the real script in --dry-run, with a STUB `uv` first on PATH.

    Not a convenience: CI installs this project with pip and has no `uv` anywhere
    (.github/workflows/ci.yml), so a test that borrows the host's would pass on a
    developer's machine and fail on the runner — which is exactly what it did. A dry run
    never executes `uv`, it only prints the plan, so a stub is the honest stand-in.
    """
    stub_bin = _stub(repo.parent / "stub-bin", "uv").parent
    _stub(stub_bin, "gh")  # same reasoning as `uv`: whether the host happens to have a
                           # `gh` must not decide if the release page is planned
    env = {**os.environ,
           "PRODUCTION_CODE": str(prod),
           "PATH": f"{stub_bin}{os.pathsep}{os.environ['PATH']}"}
    return subprocess.run(
        ["bash", str(repo / "scripts" / "shipit.sh"), "--dry-run", *args],
        cwd=str(repo), env=env, capture_output=True, text=True)


def test_version_derives_from_latest_tag_not_pyproject(tmp_path):
    repo = _make_repo(tmp_path)
    # pyproject says 0.1.1, but the latest shipped tag is 0.1.2 → patch = 0.1.3
    _git(repo, "tag", "-a", "jarvis-0.1.0", "-m", "x")
    _git(repo, "tag", "-a", "jarvis-0.1.2", "-m", "x")
    r = _dry_run(repo, tmp_path / "prod", "patch")
    assert r.returncode == 0, r.stderr
    # base is the latest tag (0.1.2), NOT pyproject (0.1.1) → patch bump is 0.1.3
    assert "jarvis-0.1.3" in r.stdout
    assert "jarvis-0.1.2 " not in r.stdout  # not re-releasing the latest tag


def test_bump_and_tag_happen_on_release_branch_not_main(tmp_path):
    repo = _make_repo(tmp_path)
    _git(repo, "tag", "-a", "jarvis-0.1.2", "-m", "x")
    r = _dry_run(repo, tmp_path / "prod", "patch")
    assert r.returncode == 0, r.stderr
    out = r.stdout
    # release branch is cut from main first, and the bump commit targets it
    assert "git branch 'release/jarvis-0.1.3'" in out
    assert "release/jarvis-0.1.3" in out
    # main must never be committed to
    assert "committing on main" not in out
    assert "commit -m 'Release jarvis-0.1.3'" in out  # the commit is planned (on the branch)


def test_notifies_telegram(tmp_path):
    repo = _make_repo(tmp_path)
    r = _dry_run(repo, tmp_path / "prod", "0.2.0")
    assert r.returncode == 0, r.stderr
    assert "telegram" in r.stdout.lower()


def test_deploys_tag_and_restarts(tmp_path):
    repo = _make_repo(tmp_path)
    r = _dry_run(repo, tmp_path / "prod", "0.2.0")
    assert r.returncode == 0, r.stderr
    out = r.stdout
    assert "checkout -f 'jarvis-0.2.0'" in out
    assert "jarvis-0.2.0" in out


def test_pushes_release_branch_and_tag_to_origin(tmp_path):
    """Git is the source of truth: nothing a release depends on stays local-only."""
    repo = _make_repo(tmp_path)
    r = _dry_run(repo, tmp_path / "prod", "0.2.0")
    assert r.returncode == 0, r.stderr
    out = r.stdout
    assert "push origin 'refs/heads/release/jarvis-0.2.0" in out
    assert "push origin 'refs/tags/jarvis-0.2.0'" in out


def test_deploys_from_the_git_remote_not_the_local_checkout(tmp_path):
    """Production tracks origin, so what runs in prod is what's on the remote."""
    repo = _make_repo(tmp_path)
    origin = str(tmp_path / "origin.git")
    r = _dry_run(repo, tmp_path / "prod", "0.2.0")
    assert r.returncode == 0, r.stderr
    out = r.stdout
    assert f"clone '{origin}'" in out
    assert f"remote set-url origin '{origin}'" in out
    assert f"clone '{repo}'" not in out


def test_refuses_when_main_is_ahead_of_origin(tmp_path):
    """An unpushed commit means the release wouldn't be reproducible from git."""
    repo = _make_repo(tmp_path)
    (repo / "local_only.txt").write_text("not pushed\n")
    _git(repo, "add", "-A")
    _git(repo, "commit", "-q", "-m", "local only")
    r = _dry_run(repo, tmp_path / "prod", "0.2.0")
    assert r.returncode != 0
    assert "origin/main" in (r.stdout + r.stderr)


def test_refuses_without_an_origin_remote(tmp_path):
    repo = _make_repo(tmp_path)
    _git(repo, "remote", "remove", "origin")
    r = _dry_run(repo, tmp_path / "prod", "0.2.0")
    assert r.returncode != 0
    assert "origin" in (r.stdout + r.stderr)


def test_os_managed_runtime_artifacts_do_not_block_a_release(tmp_path):
    """Issue 50: the OS writes into the very tree it releases from.

    This repo is a project in the production catalog, so the live daemon regenerates
    OPERATION.md and workers append to ASSUMPTIONS.md while a release is being cut.
    None of it can affect what ships — the release branch is cut from the origin/main
    COMMIT and production deploys the tag from origin — so it must not abort the run,
    and must not need a stash (the stash/pop dance is what corrupted the 0.2.1 ship).
    """
    repo = _make_repo(tmp_path)
    (repo / "OPERATION.md").write_text("<!-- regenerated at template v6 -->\n")
    (repo / "ASSUMPTIONS.md").write_text("# ASSUMPTIONS\n- [ ] (wo-x) appended mid-release\n")
    (repo / ".claude" / "settings.json").write_text('{"_jarvis": {"managed": true, "v": 6}}\n')
    r = _dry_run(repo, tmp_path / "prod", "0.2.0")
    assert r.returncode == 0, r.stdout + r.stderr
    assert "jarvis-0.2.0" in r.stdout


def test_a_serena_rewrite_of_its_own_project_file_does_not_block_a_release(tmp_path):
    """Serena reserialises `.serena/project.yml` from its own schema on every project
    activation — stripping this repo's comments and adding its current version's keys.

    It is the one exempt path the OS does not write itself, and it earns the exemption
    the same way: nobody authored it, and it is not an input to a release. It blocked
    0.10.11 twice, once after being discarded, because the next command started a
    session and Serena wrote it again — so "just revert it first" is not a workflow,
    it is a race.
    """
    repo = _make_repo(tmp_path)
    (repo / ".serena" / "project.yml").write_text(
        "language: python\nignored_paths: []\nincluded_apis: []\n")
    r = _dry_run(repo, tmp_path / "prod", "0.2.0")
    assert r.returncode == 0, r.stdout + r.stderr
    assert "jarvis-0.2.0" in r.stdout
    assert ".serena/project.yml" in r.stdout, "exempted drift must still be named"


def test_an_authored_edit_elsewhere_in_serena_still_blocks(tmp_path):
    """The exemption is that one FILE, not the directory. A committed memory is
    hand-written prose the repo ships, and losing one to a silent exemption is exactly
    the risk the narrow list exists to avoid."""
    repo = _make_repo(tmp_path)
    (repo / ".serena" / "memories").mkdir(parents=True)
    (repo / ".serena" / "memories" / "codebase-map.md").write_text("# map\n")
    _git(repo, "add", "-A")
    _git(repo, "commit", "-q", "-m", "memory")
    (repo / ".serena" / "memories" / "codebase-map.md").write_text("# map\nedited\n")
    r = _dry_run(repo, tmp_path / "prod", "0.2.0")
    assert r.returncode != 0
    assert "codebase-map.md" in (r.stdout + r.stderr)


def test_ignored_os_managed_paths_are_reported_by_name(tmp_path):
    """Drift stays visible: swallowed silently, it would rot unnoticed."""
    repo = _make_repo(tmp_path)
    (repo / "OPERATION.md").write_text("<!-- regenerated -->\n")
    (repo / "ASSUMPTIONS.md").write_text("# ASSUMPTIONS\n- [ ] (wo-x) something\n")
    r = _dry_run(repo, tmp_path / "prod", "0.2.0")
    assert r.returncode == 0, r.stdout + r.stderr
    out = r.stdout
    assert "ignoring" in out.lower()
    assert "OPERATION.md" in out
    assert "ASSUMPTIONS.md" in out
    # only what was actually dirty is reported, not the whole list
    assert ".claude/settings.json" not in out


def test_authored_edits_outside_the_list_still_block_a_release(tmp_path):
    """The guard still does its job: only the declared OS artifacts are exempt."""
    repo = _make_repo(tmp_path)
    (repo / "OPERATION.md").write_text("<!-- regenerated -->\n")   # exempt
    (repo / "README.md").write_text("# dev\nan authored edit\n")   # not exempt
    r = _dry_run(repo, tmp_path / "prod", "0.2.0")
    assert r.returncode != 0
    err = r.stdout + r.stderr
    assert "tracked changes present" in err
    assert "README.md" in err


def test_staged_authored_edits_outside_the_list_still_block_a_release(tmp_path):
    repo = _make_repo(tmp_path)
    (repo / "README.md").write_text("# dev\nstaged authored edit\n")
    _git(repo, "add", "README.md")
    r = _dry_run(repo, tmp_path / "prod", "0.2.0")
    assert r.returncode != 0
    assert "README.md" in (r.stdout + r.stderr)


def test_daemon_restart_is_detached_from_this_script(tmp_path):
    """The 0.5.0 ship was half-applied by this exact trap.

    shipit is usually run from a Claude session that Jarvis itself spawned, and that
    session lives inside `jarvis.service`'s cgroup — so `systemctl --user restart
    jarvis.service` SIGTERMs the running script. The daemon restart must therefore be
    handed to a transient systemd unit that lives OUTSIDE our cgroup, so it completes
    whether or not we survive it.
    """
    repo = _make_repo(tmp_path)
    r = _dry_run(repo, tmp_path / "prod", "0.2.0")
    assert r.returncode == 0, r.stderr
    out = r.stdout
    assert "systemd-run --user" in out
    assert "restart jarvis.service" in out
    # never restarted inline: that is the command that kills us
    assert "systemctl --user restart 'jarvis.service'" not in out


def test_everything_else_finishes_before_the_daemon_restart(tmp_path):
    """Order is the other half of the fix.

    Whatever the script still has to do after restarting the daemon is work it may
    never get to. The UI restart and the Telegram notification must both happen first.
    """
    repo = _make_repo(tmp_path)
    r = _dry_run(repo, tmp_path / "prod", "0.2.0")
    assert r.returncode == 0, r.stderr
    out = r.stdout
    daemon = out.index("systemd-run --user")
    assert out.index("jarvis-ui.service") < daemon
    assert out.lower().index("telegram") < daemon


def test_ui_restarts_inline_and_is_verified(tmp_path):
    """The UI never hosts this script, so its restart can be run and checked here."""
    repo = _make_repo(tmp_path)
    r = _dry_run(repo, tmp_path / "prod", "0.2.0")
    assert r.returncode == 0, r.stderr
    out = r.stdout
    assert "systemctl --user restart 'jarvis-ui.service'" in out
    assert "status 'jarvis-ui.service'" in out


def test_explicit_version_is_respected(tmp_path):
    repo = _make_repo(tmp_path)
    _git(repo, "tag", "-a", "jarvis-0.1.2", "-m", "x")
    r = _dry_run(repo, tmp_path / "prod", "1.5.0")
    assert r.returncode == 0, r.stderr
    assert "jarvis-1.5.0" in r.stdout


# -- re-rendering the units ------------------------------------------------------
#
# Installing the units was a one-time manual step, so #90's `gh` PATH fix sat in
# install_prod_service.sh unapplied for a release and a half while every worker kept
# getting a bash with no `gh`. A release is the one moment the two are guaranteed to be
# looked at together.


def _deployed(tmp_path: Path) -> Path:
    """A production root already carrying the installer, as every current tag does.

    Step 5a only re-renders what the deployed tag can render, so which branch it takes
    is decided by this file — not by whether the machine running the test happens to
    have jarvis units installed. That distinction is what made the first version of
    these tests pass locally and fail on CI.
    """
    prod = tmp_path / "prod"
    (prod / "jarvis_os" / "scripts").mkdir(parents=True)
    (prod / "jarvis_os" / "scripts" / "install_prod_service.sh").write_text("#!/bin/sh\n")
    return prod


def test_the_units_are_re_rendered_from_the_deployed_tag(tmp_path):
    """From PROD_DIR, not this checkout: the units must describe the version going live,
    and after step 5 that is what is checked out there."""
    repo = _make_repo(tmp_path)
    prod = _deployed(tmp_path)
    r = _dry_run(repo, prod, "0.2.0")
    assert r.returncode == 0, r.stderr

    assert f"{prod}/jarvis_os/scripts/install_prod_service.sh' --no-restart" in r.stdout


def test_the_re_render_happens_before_anything_is_restarted(tmp_path):
    """A unit rendered after the restart is a unit that takes effect a release late —
    which is the same silent lag this whole step exists to remove."""
    repo = _make_repo(tmp_path)
    r = _dry_run(repo, _deployed(tmp_path), "0.2.0")
    out = r.stdout

    assert out.index("install_prod_service.sh") < out.index("restart 'jarvis-ui.service'")
    assert out.index("install_prod_service.sh") < out.index("systemd-run --user")


def test_a_staged_release_re_renders_too(tmp_path):
    """`--stage` exits before the restarts and hands them to the daemon (release.py).
    The units have to be written by then, because that restart is what reads them."""
    repo = _make_repo(tmp_path)
    r = _dry_run(repo, _deployed(tmp_path), "0.2.0", "--stage", "--wo", "wo-1234abcd")
    assert r.returncode == 0, r.stderr

    assert "install_prod_service.sh' --no-restart" in r.stdout
    assert "services NOT restarted" in r.stdout


def test_a_tag_without_the_installer_says_so_instead_of_aborting(tmp_path):
    """A tag old enough to predate install_prod_service.sh is still legal to deploy, and
    failing a release over a re-render would be the worse bug. But silence about the
    units is precisely what this step exists to end, so it has to say which it did."""
    repo = _make_repo(tmp_path)
    r = _dry_run(repo, tmp_path / "prod", "0.2.0")   # no installer deployed

    assert r.returncode == 0, r.stderr
    assert "units NOT re-rendered" in r.stdout
    assert "jarvis doctor" in r.stdout
    assert "--no-restart" not in r.stdout, "claimed a re-render it could not do"


# -- the tag's uv.lock -----------------------------------------------------------
#
# Issue #202: nine releases shipped a lock recording jarvis-os 0.1.1 beside a pyproject
# recording the released version, because the bump committed pyproject ALONE. Any bare
# `uv` command in the production checkout then re-resolved and rewrote the lock, leaving
# prod dirty and every version string suffixed `-dirty`.


def test_the_release_commit_carries_the_relocked_uv_lock(tmp_path):
    repo = _make_repo(tmp_path)
    r = _dry_run(repo, tmp_path / "prod", "0.2.0")
    assert r.returncode == 0, r.stderr
    assert "uv lock" in r.stdout
    assert "add pyproject.toml uv.lock" in r.stdout


def test_the_relock_happens_before_the_commit(tmp_path):
    """A lock written after the commit is a lock that does not reach the tag."""
    repo = _make_repo(tmp_path)
    r = _dry_run(repo, tmp_path / "prod", "0.2.0")
    out = r.stdout
    assert out.index("uv lock") < out.index("commit -m 'Release jarvis-0.2.0'")


#: Everything the script reaches for before the tool preconditions run. The sandbox PATH
#: holds only these, so "not found" means the test withheld it and nothing else.
_PRECONDITION_TOOLS = ("dirname", "git", "sed", "grep", "sort", "tail", "mktemp")


def _run_with_only(tmp_path: Path, repo: Path, *, keep: tuple[str, ...],
                   stub: tuple[str, ...]) -> subprocess.CompletedProcess[str]:
    """Drive the script with a PATH holding only what this test planted.

    `stub` rather than `keep` for `uv`: CI has none to borrow, so a test that symlinked
    the host's would assert the wrong precondition there — it would fail on the missing
    `uv` while claiming to be about something else.
    """
    sandbox = tmp_path / "bin"
    sandbox.mkdir(exist_ok=True)
    for tool in keep:
        real = shutil.which(tool)
        if real and not (sandbox / tool).exists():
            (sandbox / tool).symlink_to(real)
    for name in stub:
        _stub(sandbox, name)
    return subprocess.run(
        [BASH, str(repo / "scripts" / "shipit.sh"), "--dry-run", "0.2.0"],
        cwd=str(repo), capture_output=True, text=True,
        env={"PATH": str(sandbox), "HOME": str(tmp_path / "home"),
             "PRODUCTION_CODE": str(tmp_path / "prod")})


# -- the release page (what GitHub shows as this version's changelog) ------------
#
# Pushing a tag leaves /releases empty: there is no per-version page, and no way to
# see what a version contains without reading git by hand. shipit therefore publishes
# a GitHub release for every tag it cuts, with notes built from the commits main
# gained since the previous release.


def test_publishes_a_github_release_for_the_tag(tmp_path):
    repo = _make_repo(tmp_path)
    _git(repo, "tag", "-a", "jarvis-0.1.2", "-m", "x")
    r = _dry_run(repo, tmp_path / "prod", "patch")
    assert r.returncode == 0, r.stderr
    assert "gh release create 'jarvis-0.1.3'" in r.stdout
    assert "Jarvis OS 0.1.3" in r.stdout


def test_the_release_notes_list_what_landed_since_the_previous_release(tmp_path):
    repo = _make_repo(tmp_path)
    _tag_like_shipit(repo, "0.1.2")
    _commit(repo, "Teach the gate about spent grants (#516)")
    _commit(repo, "Cap the finish summary (#574)")
    _git(repo, "push", "-q", "origin", "main")
    r = _dry_run(repo, tmp_path / "prod", "patch")
    assert r.returncode == 0, r.stderr
    assert "Teach the gate about spent grants (#516)" in r.stdout
    assert "Cap the finish summary (#574)" in r.stdout


def test_the_release_notes_exclude_what_the_previous_release_already_shipped(tmp_path):
    """The range is anchored on the previous TAG, which does not sit on main."""
    repo = _make_repo(tmp_path)
    _commit(repo, "Shipped back in 0.1.2")
    _tag_like_shipit(repo, "0.1.2")
    _commit(repo, "Landed after 0.1.2")
    _git(repo, "push", "-q", "origin", "main")
    r = _dry_run(repo, tmp_path / "prod", "patch")
    assert r.returncode == 0, r.stderr
    assert "Landed after 0.1.2" in r.stdout
    assert "Shipped back in 0.1.2" not in r.stdout
    # the previous release's own bump commit is not a change this release makes
    assert "- Release jarvis-0.1.2" not in r.stdout


def test_the_first_release_still_gets_notes(tmp_path):
    """No previous tag to anchor on — the notes cover the history, not nothing."""
    repo = _make_repo(tmp_path)
    _commit(repo, "The very first thing")
    _git(repo, "push", "-q", "origin", "main")
    r = _dry_run(repo, tmp_path / "prod", "0.1.0")
    assert r.returncode == 0, r.stderr
    assert "gh release create 'jarvis-0.1.0'" in r.stdout
    assert "The very first thing" in r.stdout


def test_the_release_is_published_after_the_tag_reaches_origin(tmp_path):
    """gh attaches the page to a tag the REMOTE already carries (--verify-tag)."""
    repo = _make_repo(tmp_path)
    r = _dry_run(repo, tmp_path / "prod", "0.2.0")
    assert r.returncode == 0, r.stderr
    out = r.stdout
    assert out.index("push origin 'refs/tags/jarvis-0.2.0'") < out.index("gh release create")


def test_a_staged_release_is_published_too(tmp_path):
    """--stage hands the restarts to the daemon, not the changelog."""
    repo = _make_repo(tmp_path)
    r = _dry_run(repo, tmp_path / "prod", "--stage", "--wo", "wo-abc123", "0.2.0")
    assert r.returncode == 0, r.stderr
    assert "gh release create 'jarvis-0.2.0'" in r.stdout


def test_a_missing_gh_does_not_abort_the_release(tmp_path):
    """A release page is a record, not a precondition for running code."""
    repo = _make_repo(tmp_path)
    r = _run_with_only(tmp_path, repo,
                       keep=(*_PRECONDITION_TOOLS, "diff"), stub=("uv",))
    assert r.returncode == 0, r.stderr
    out = r.stdout
    assert "gh not found" in out
    assert "gh release create jarvis-0.2.0" in out   # the command to run by hand later
    assert "deploying to" in out                      # and the deploy carried on


def test_refuses_when_uv_is_not_on_path(tmp_path):
    """Checked in the preconditions, not at first use: `uv sync` needs it too, and by
    then the tag has already been pushed to origin."""
    repo = _make_repo(tmp_path)
    r = _run_with_only(tmp_path, repo, keep=(*_PRECONDITION_TOOLS, "diff"), stub=())
    assert r.returncode != 0
    assert "uv not found" in (r.stdout + r.stderr)


# -- the guard that keeps the relock honest --------------------------------------
#
# `uv lock` is free to move every dependency it likes. A release commit that does so
# silently is a worse bug than the one above, so the script asserts the relocked file is
# what HEAD's lock looks like with the version line — and nothing else — rewritten.
# Sliced out of the real script rather than copied: a copy keeps passing after the
# original changes, which is the standard way a shell-script test becomes a lie.

_LOCK_GUARD_START = "# >>> lock-guard"
_LOCK_GUARD_END = "# <<< lock-guard"

_LOCK = """version = 1
requires-python = ">=3.13"

[[package]]
name = "httpx"
version = "0.27.0"
source = { registry = "https://pypi.org/simple" }

[[package]]
name = "jarvis-os"
version = "0.1.1"
source = { editable = "." }
"""


def _lock_guard_source() -> str:
    text = SHIPIT.read_text()
    start, end = text.find(_LOCK_GUARD_START), text.find(_LOCK_GUARD_END)
    assert start >= 0, f"{_LOCK_GUARD_START} missing from scripts/shipit.sh"
    assert end > start, f"{_LOCK_GUARD_END} missing or misplaced in scripts/shipit.sh"
    return text[start:end]


def _run_guard(worktree: Path, version: str) -> subprocess.CompletedProcess[str]:
    script = (
        "set -euo pipefail\n"
        "die() { printf '%s\\n' \"$*\" >&2; exit 1; }\n"
        + _lock_guard_source()
        + f"\nassert_lock_bump_only {worktree!s} {version}\n"
    )
    return subprocess.run([BASH, "-c", script], capture_output=True, text=True)


@pytest.fixture()
def locked(tmp_path: Path) -> Path:
    """A release worktree whose HEAD carries a lock, mid-bump: the file on disk is
    whatever `uv lock` just wrote, HEAD's copy is what main had."""
    wt = tmp_path / "wt"
    wt.mkdir()
    (wt / "uv.lock").write_text(_LOCK)
    _git(wt, "init", "-q", "-b", "main")
    _git(wt, "config", "user.email", "t@example.com")
    _git(wt, "config", "user.name", "Test")
    _git(wt, "add", "-A")
    _git(wt, "commit", "-q", "-m", "init")
    return wt


def test_guard_accepts_a_lock_that_only_moved_the_root_version(locked):
    (locked / "uv.lock").write_text(_LOCK.replace('version = "0.1.1"', 'version = "0.2.0"'))
    r = _run_guard(locked, "0.2.0")
    assert r.returncode == 0, r.stdout + r.stderr


def test_guard_refuses_a_relock_that_moved_a_dependency(locked):
    """The failure mode worth aborting a release for: a dependency reaching production
    inside a release commit, with no review and no record."""
    (locked / "uv.lock").write_text(
        _LOCK.replace('version = "0.1.1"', 'version = "0.2.0"')
             .replace('version = "0.27.0"', 'version = "0.28.0"'))
    r = _run_guard(locked, "0.2.0")
    assert r.returncode != 0
    err = r.stdout + r.stderr
    assert "re-resolved more than the version bump" in err
    assert "0.28.0" in err, "the offending change must be shown, not just named"


def test_guard_refuses_a_lock_left_at_the_old_version(locked):
    """`uv lock` not running at all is the bug this whole change fixes."""
    r = _run_guard(locked, "0.2.0")
    assert r.returncode != 0
    assert "0.1.1" in (r.stdout + r.stderr)


def test_guard_refuses_when_the_relock_wrote_no_file(locked):
    """It must FAIL CLOSED. `diff` against a missing file produces no differing lines,
    so a guard that only looked at the output would wave the release through."""
    (locked / "uv.lock").unlink()
    r = _run_guard(locked, "0.2.0")
    assert r.returncode != 0
    assert "left no" in (r.stdout + r.stderr)


@pytest.mark.skipif(os.geteuid() == 0, reason="root can read a 000 file")
def test_guard_refuses_when_diff_cannot_compare_at_all(locked):
    """diff exits >1 when it could not do the comparison. Same fail-closed rule: an
    unmade comparison is not a passed one."""
    (locked / "uv.lock").write_text(_LOCK.replace('version = "0.1.1"', 'version = "0.2.0"'))
    (locked / "uv.lock").chmod(0o000)
    try:
        r = _run_guard(locked, "0.2.0")
    finally:
        (locked / "uv.lock").chmod(0o644)
    assert r.returncode != 0
    assert "cannot compare" in (r.stdout + r.stderr)


def test_refuses_when_diff_is_not_on_path(tmp_path):
    """A guard that cannot run must stop the release, not be skipped."""
    repo = _make_repo(tmp_path)
    r = _run_with_only(tmp_path, repo, keep=_PRECONDITION_TOOLS, stub=("uv",))
    assert r.returncode != 0
    assert "diff not found" in (r.stdout + r.stderr)


def test_guard_refuses_when_head_carries_no_lock_at_all(tmp_path):
    wt = tmp_path / "wt"
    wt.mkdir()
    (wt / "README.md").write_text("# x\n")
    _git(wt, "init", "-q", "-b", "main")
    _git(wt, "config", "user.email", "t@example.com")
    _git(wt, "config", "user.name", "Test")
    _git(wt, "add", "-A")
    _git(wt, "commit", "-q", "-m", "init")
    (wt / "uv.lock").write_text(_LOCK)
    r = _run_guard(wt, "0.2.0")
    assert r.returncode != 0
    assert "no uv.lock at HEAD" in (r.stdout + r.stderr)
