#!/usr/bin/env bash
# shipit — cut a Jarvis OS release from ALREADY-merged main and deploy it to production.
#
# Releases never bypass code review: the code changes must already be on main via a
# reviewed PR before you run this. shipit only does the release-cut + deploy:
#
#   1. Verify the tree is clean, that HEAD is exactly origin/main, and resolve the
#      target version X.Y.Z (from the latest jarvis-* tag — main's pyproject is NOT
#      bumped by shipit).
#   2. Cut branch  release/jarvis-X.Y.Z  from main.
#   3. Bump pyproject.toml + commit + annotated tag  jarvis-X.Y.Z  *on the release
#      branch* — main is never modified (done in a throwaway git worktree so the
#      shared main checkout's HEAD never moves).
#   4. Push the release branch AND the tag to origin.
#   5. Deploy the tag to  $PRODUCTION_CODE/jarvis_os  from ORIGIN (clone on first run,
#      then fetch + checkout the tag + `uv sync`), and restart the systemd services.
#   6. Notify Telegram (best-effort).
#
# GIT IS THE SOURCE OF TRUTH. Every ref a release depends on lives on the remote:
# shipit refuses to run if HEAD isn't origin/main, pushes the release branch and tag
# before deploying, and production tracks `origin` — so what runs in prod is exactly
# what is on the remote, reproducible from any machine.
#
# Usage:
#   scripts/shipit.sh                 # patch-bump from the latest jarvis-* tag
#   scripts/shipit.sh 1.2.0           # release an explicit version
#   scripts/shipit.sh patch|minor|major
#   scripts/shipit.sh --dry-run [ver] # print what would happen, change nothing
#
# Env:
#   PRODUCTION_CODE   production root (default: ~/workspace/production)
set -euo pipefail

DRY_RUN=0
BUMP_OR_VERSION=""
for arg in "$@"; do
  case "$arg" in
    --dry-run) DRY_RUN=1 ;;
    *) BUMP_OR_VERSION="$arg" ;;
  esac
done

REPO="$(git -C "$(dirname "${BASH_SOURCE[0]}")" rev-parse --show-toplevel)"
cd "$REPO"

PRODUCTION_CODE="${PRODUCTION_CODE:-$HOME/workspace/production}"
PROD_ROOT="$PRODUCTION_CODE"
PROD_DIR="$PROD_ROOT/jarvis_os"
PROD_CONFIG="$PROD_ROOT/config/catalog.json"
PROD_SECRETS="$PROD_ROOT/secrets/jarvis.env"

say()  { printf '\033[1;36m▶ %s\033[0m\n' "$*"; }
run()  { if [ "$DRY_RUN" = 1 ]; then printf '  [dry-run] %s\n' "$*"; else eval "$*"; fi; }
die()  { printf '\033[1;31m✗ %s\033[0m\n' "$*" >&2; exit 1; }

# --- 1. preconditions -----------------------------------------------------------
BRANCH="$(git rev-parse --abbrev-ref HEAD)"
[ "$BRANCH" = "main" ] || say "warning: shipping from '$BRANCH', not 'main' (releases cut from merged main)"

# Runtime artifacts the OS writes into the trees it manages. This repo is registered
# as a project in the PRODUCTION catalog, so the live daemon and its workers rewrite
# these files in the very checkout we release from:
#
#   OPERATION.md           regenerated by bootstrap_project() on `jarvis start`,
#                          whenever the committed copy's template version lags
#   ASSUMPTIONS.md         appended by `jarvis wo assume`
#   .claude/settings.json  the OS baseline deep-merged in by bootstrap_project()
#
# Ignoring them carries no shipping risk: the release branch is cut from the
# origin/main COMMIT, the bump+tag happen in a throwaway worktree, and production
# deploys the tag from ORIGIN — this working tree is never an input to a release.
# The guard below only asks "do you have uncommitted work you care about", and
# OS-injected drift is not such work. We still print every ignored path by name so
# the drift stays visible, and still hard-fail on anything outside this list.
#
# Stopping the OS from dirtying the tree at all is the deeper fix, and is tracked
# separately — see GitHub issue 50 (gonandrap/agentic_os).
OS_MANAGED_PATHS=(OPERATION.md ASSUMPTIONS.md .claude/settings.json)

IGNORED=(); BLOCKING=()
while IFS= read -r p; do
  [ -n "$p" ] || continue
  listed=0
  for m in "${OS_MANAGED_PATHS[@]}"; do
    [ "$p" = "$m" ] && { listed=1; break; }
  done
  if [ "$listed" = 1 ]; then IGNORED+=("$p"); else BLOCKING+=("$p"); fi
done < <({ git -c core.quotePath=false diff --name-only
           git -c core.quotePath=false diff --cached --name-only; } | sort -u)

if [ "${#IGNORED[@]}" -gt 0 ]; then
  say "ignoring dirty OS-managed runtime artifacts (not authored edits, not an input to the release):"
  for p in "${IGNORED[@]}"; do printf '    %s\n' "$p"; done
fi
if [ "${#BLOCKING[@]}" -gt 0 ]; then
  die "tracked changes present — releases are cut from a clean, already-merged main:
$(printf '     %s\n' "${BLOCKING[@]}")"
fi

# Git is the source of truth: a release must be reproducible from the remote alone.
ORIGIN_URL="$(git remote get-url origin 2>/dev/null)" \
  || die "no 'origin' remote — git is the source of truth for releases"
say "syncing with origin ($ORIGIN_URL)"
git fetch origin --tags --prune --quiet || die "cannot fetch origin — releases require the remote"
git rev-parse -q --verify refs/remotes/origin/main >/dev/null \
  || die "origin/main not found on $ORIGIN_URL"
if [ "$(git rev-parse HEAD)" != "$(git rev-parse origin/main)" ]; then
  die "HEAD is not origin/main — land the code on main via a merged PR and pull first
     (local $(git rev-parse --short HEAD) vs origin/main $(git rev-parse --short origin/main))"
fi

cur_version()   { grep -m1 -E '^version *= *"' pyproject.toml | sed -E 's/.*"([^"]+)".*/\1/'; }
latest_tagged() {  # highest X.Y.Z among jarvis-* tags, empty if none
  git tag -l 'jarvis-*' | sed -E 's/^jarvis-//' \
    | { grep -E '^[0-9]+\.[0-9]+\.[0-9]+$' || true; } | sort -V | tail -1
}

bump() {  # bump <X.Y.Z> <major|minor|patch>
  local IFS=.; read -r ma mi pa <<<"$1"
  case "$2" in
    major) echo "$((ma+1)).0.0" ;;
    minor) echo "$ma.$((mi+1)).0" ;;
    patch) echo "$ma.$mi.$((pa+1))" ;;
  esac
}

# Version numbering derives from the latest release TAG, not pyproject.toml — main's
# pyproject is never bumped by shipit (the bump lives only on release branches).
BASE="$(latest_tagged)"; BASE="${BASE:-$(cur_version)}"
case "$BUMP_OR_VERSION" in
  "")                   VERSION="$(bump "$BASE" patch)" ;;
  major|minor|patch)    VERSION="$(bump "$BASE" "$BUMP_OR_VERSION")" ;;
  [0-9]*.[0-9]*.[0-9]*) VERSION="$BUMP_OR_VERSION" ;;
  *) die "invalid version/bump: '$BUMP_OR_VERSION' (want X.Y.Z or major|minor|patch)" ;;
esac

TAG="jarvis-$VERSION"
REL_BRANCH="release/jarvis-$VERSION"
git rev-parse -q --verify "refs/tags/$TAG" >/dev/null && die "tag $TAG already exists"
git rev-parse -q --verify "refs/heads/$REL_BRANCH" >/dev/null && die "branch $REL_BRANCH already exists"

MAIN_SHA="$(git rev-parse HEAD)"
say "Releasing Jarvis OS $VERSION  (base tag: ${BASE}, from $BRANCH ${MAIN_SHA:0:9})"
say "  branch: $REL_BRANCH   tag: $TAG"
say "  deploy: $PROD_DIR"

# --- 2. cut the release branch from main ----------------------------------------
say "cutting release branch $REL_BRANCH from $BRANCH"
run "git branch '$REL_BRANCH' '$MAIN_SHA'"

# --- 3. bump + commit + tag ON the release branch (main is never modified) -------
# Use a throwaway worktree so the shared main checkout's HEAD/tree never moves.
say "bumping pyproject.toml → $VERSION and committing on $REL_BRANCH (main untouched)"
if [ "$DRY_RUN" = 1 ]; then WT="<tmp-worktree>"; else WT="$(mktemp -d)"; fi
cleanup() { [ "$DRY_RUN" != 1 ] && [ -n "${WT:-}" ] && [ -d "$WT" ] \
              && git worktree remove --force "$WT" 2>/dev/null || true; }
trap cleanup EXIT
run "git worktree add --quiet '$WT' '$REL_BRANCH'"
run "sed -i -E '0,/^version *= *\"[^\"]+\"/s//version = \"$VERSION\"/' '$WT/pyproject.toml'"
run "git -C '$WT' add pyproject.toml"
run "git -C '$WT' commit -m 'Release jarvis-$VERSION'"
say "tagging $TAG on $REL_BRANCH"
run "git -C '$WT' tag -a '$TAG' -m 'Jarvis OS $VERSION'"
run "git worktree remove --force '$WT'"

# --- 4. push to origin (git is the source of truth) ------------------------------
# Do this BEFORE deploying: production pulls from the remote, so an unpushed ref
# would mean shipping something no one else can reproduce.
say "pushing $REL_BRANCH and $TAG to origin"
run "git push origin 'refs/heads/$REL_BRANCH:refs/heads/$REL_BRANCH'"
run "git push origin 'refs/tags/$TAG'"

# --- 5. deploy to production (from origin, not this checkout) --------------------
say "deploying to $PROD_DIR"
run "mkdir -p '$PROD_ROOT'"
if [ ! -d "$PROD_DIR/.git" ]; then
  say "first deploy — cloning $ORIGIN_URL into $PROD_DIR"
  run "git clone '$ORIGIN_URL' '$PROD_DIR'"
fi
# keep prod pointed at the remote, even if it was first cloned from a local path
run "git -C '$PROD_DIR' remote set-url origin '$ORIGIN_URL'"
run "git -C '$PROD_DIR' fetch origin --tags --prune --force"
run "git -C '$PROD_DIR' checkout -f '$TAG'"
say "building production venv (uv sync --frozen --extra ui)"
run "(cd '$PROD_DIR' && uv sync --frozen --extra ui)"

# default production catalog (empty fleet until prod onboarding lands)
if [ ! -f "$PROD_CONFIG" ]; then
  say "creating default production catalog at $PROD_CONFIG"
  run "mkdir -p '$PROD_ROOT/config'"
  if [ "$DRY_RUN" != 1 ]; then
    cat > "$PROD_CONFIG" <<'JSON'
{
  "$comment": "Production fleet catalog. Projects under $PRODUCTION_CODE get added here (prod onboarding — future). Empty is valid.",
  "os": {
    "defaults": { "model": "claude-opus-5", "permission_mode": "auto" },
    "notifications": {
      "sinks": ["log", "telegram"],
      "telegram": { "token_env": "JARVIS_TELEGRAM_TOKEN", "chat_id_env": "JARVIS_TELEGRAM_CHAT_ID" }
    },
    "ui": { "port": 8787 }
  },
  "projects": []
}
JSON
  fi
fi

# --- 6. restart the UI (safe to do inline: it does not host this script) ---------
#
# WHY THE DAEMON IS NOT RESTARTED HERE. shipit is usually run from a Claude session
# that Jarvis itself spawned, and such a session lives inside jarvis.service's cgroup.
# `systemctl --user restart jarvis.service` therefore SIGTERMs this very script: the
# daemon comes back on the new tag, everything the script had left to do never runs.
# That is exactly how 0.5.0 shipped half-applied — the daemon restarted, the script
# died, and jarvis-ui.service kept serving the old code.
#
# So the restart step is split in two, and the daemon goes LAST (step 8), detached:
#   * jarvis-ui.service never hosts us → restart it inline and verify it here;
#   * jarvis.service may host us → hand its restart to a transient systemd unit that
#     lives outside our cgroup, after everything else is done.
unit_installed() {  # unit_installed <unit>; a dry run always prints the full plan
  if [ "$DRY_RUN" = 1 ]; then return 0; fi
  systemctl --user list-unit-files "$1" 2>/dev/null | grep -q "$1"
}

UI_SVC="jarvis-ui.service"
DAEMON_SVC="jarvis.service"

any_installed=0
if unit_installed "$UI_SVC"; then
  any_installed=1
  say "restarting $UI_SVC"
  run "systemctl --user restart '$UI_SVC'"
  [ "$DRY_RUN" = 1 ] || sleep 2
  run "systemctl --user --no-pager --lines=0 status '$UI_SVC' || true"
fi
if unit_installed "$DAEMON_SVC"; then any_installed=1; fi
if [ "$any_installed" = 0 ]; then
  say "services not installed — run scripts/install_prod_service.sh once to enable them"
fi

# --- 7. notify Telegram (best-effort) -------------------------------------------
notify_telegram() {
  local text="🚀 Shipped $TAG to production ($PROD_DIR)"
  if [ "$DRY_RUN" = 1 ]; then
    run "curl telegram sendMessage: $text"
    return 0
  fi
  [ -f "$PROD_SECRETS" ] || { say "telegram: no secrets at $PROD_SECRETS — skipped"; return 0; }
  # shellcheck disable=SC1090
  set -a; . "$PROD_SECRETS"; set +a
  local tok="${JARVIS_TELEGRAM_TOKEN:-}" chat="${JARVIS_TELEGRAM_CHAT_ID:-}"
  if [ -z "$tok" ] || [ -z "$chat" ]; then
    say "telegram: token/chat_id not in $PROD_SECRETS — skipped"; return 0
  fi
  if curl -sS --max-time 15 "https://api.telegram.org/bot${tok}/sendMessage" \
       -d "chat_id=${chat}" -d "text=${text}" >/dev/null 2>&1; then
    say "telegram: notified"
  else
    say "telegram: send failed (non-fatal)"
  fi
}
say "notifying telegram"
notify_telegram

say "shipped $TAG → $PROD_DIR"
[ "$DRY_RUN" = 1 ] && say "(dry-run: no changes were made)"

# --- 8. restart the daemon LAST, detached from this script ----------------------
# Nothing may follow this step: if we are running inside jarvis.service's cgroup the
# restart kills us. `systemd-run --user` puts the restart in its own transient unit,
# outside our cgroup, so it completes whether or not we survive; the short sleep lets
# this script print its last line and exit cleanly first.
if unit_installed "$DAEMON_SVC"; then
  if [ "$DRY_RUN" != 1 ] && ! command -v systemd-run >/dev/null 2>&1; then
    say "systemd-run unavailable — restarting $DAEMON_SVC inline (this script may be killed)"
    run "systemctl --user restart '$DAEMON_SVC'"
  else
    say "restarting $DAEMON_SVC (detached — this script may live in its cgroup)"
    run "systemd-run --user --collect --unit='jarvis-shipit-restart-${VERSION//./-}' \
           --description='shipit $TAG: restart $DAEMON_SVC' \
           /bin/sh -c 'sleep 3; systemctl --user restart $DAEMON_SVC'"
    say "  queued: $DAEMON_SVC restarts in ~3s — check with: systemctl --user status $DAEMON_SVC"
  fi
fi
exit 0
