"""Project bootstrap ("adopt"): make a project OS-ready, idempotently.

- README.md         required; stub generated when missing
- OPERATION.md      the operating contract, generated from a versioned template
- .jarvis/          per-project state dir, added to .gitignore
- .claude/settings.json  injected: OS baseline deep-merged with catalog overrides,
                    marked with a "_jarvis" key (managed flag + content hash) so
                    manual drift is detected on the next start
"""

from __future__ import annotations

import hashlib
import json
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

from .catalog import ProjectSpec

TEMPLATE_VERSION = 1
ASSETS = Path(__file__).parent / "assets"


@dataclass
class BootstrapReport:
    project: str
    actions: list[str] = field(default_factory=list)
    warnings: list[str] = field(default_factory=list)

    def note(self, msg: str) -> None:
        self.actions.append(msg)

    def warn(self, msg: str) -> None:
        self.warnings.append(msg)


def deep_merge(base: dict[str, Any], override: dict[str, Any]) -> dict[str, Any]:
    """Recursive dict merge; override wins; lists and scalars are replaced."""
    out = dict(base)
    for k, v in override.items():
        if isinstance(v, dict) and isinstance(out.get(k), dict):
            out[k] = deep_merge(out[k], v)
        else:
            out[k] = v
    return out


def _settings_hash(settings: dict[str, Any]) -> str:
    clean = {k: v for k, v in settings.items() if k != "_jarvis"}
    return hashlib.sha256(json.dumps(clean, sort_keys=True).encode()).hexdigest()[:16]


def build_settings(overrides: dict[str, Any]) -> dict[str, Any]:
    base = json.loads((ASSETS / "settings.base.json").read_text())
    base.pop("$comment", None)
    merged = deep_merge(base, overrides)
    merged["_jarvis"] = {"managed": True, "version": TEMPLATE_VERSION}
    merged["_jarvis"]["hash"] = _settings_hash(merged)
    return merged


def settings_drift(settings_path: Path) -> str | None:
    """Return a drift description if the injected settings were manually edited."""
    if not settings_path.exists():
        return "missing"
    try:
        current = json.loads(settings_path.read_text())
    except json.JSONDecodeError:
        return "unparseable"
    marker = current.get("_jarvis")
    if not isinstance(marker, dict) or not marker.get("managed"):
        return "not managed by jarvis"
    if marker.get("hash") != _settings_hash(current):
        return "manually edited since injection"
    return None


def inject_settings(project: ProjectSpec, report: BootstrapReport, force: bool = False) -> None:
    claude_dir = project.path / ".claude"
    claude_dir.mkdir(exist_ok=True)
    settings_path = claude_dir / "settings.json"
    desired = build_settings(project.settings_overrides)

    if settings_path.exists():
        drift = settings_drift(settings_path)
        current_text = settings_path.read_text()
        if current_text.strip() == json.dumps(desired, indent=2).strip():
            report.note("settings.json already up to date")
            return
        if drift in ("not managed by jarvis",):
            backup = claude_dir / "settings.json.pre-jarvis"
            if not backup.exists():
                backup.write_text(current_text)
                report.note(f"backed up existing settings to {backup.name}")
        elif drift == "manually edited since injection" and not force:
            report.warn(
                "settings.json was manually edited since Jarvis injected it — "
                "re-run with --force-config to overwrite (put customizations in the "
                "catalog's settings_overrides instead)"
            )
            return
    settings_path.write_text(json.dumps(desired, indent=2) + "\n")
    report.note("injected .claude/settings.json")


def ensure_gitignore(project: ProjectSpec, report: BootstrapReport) -> None:
    gi = project.path / ".gitignore"
    line = ".jarvis/"
    text = gi.read_text() if gi.exists() else ""
    if line not in text.split("\n"):
        with gi.open("a") as f:
            if text and not text.endswith("\n"):
                f.write("\n")
            f.write(f"\n# Jarvis OS local state\n{line}\n")
        report.note("added .jarvis/ to .gitignore")


def ensure_readme(project: ProjectSpec, report: BootstrapReport) -> None:
    readme = project.path / "README.md"
    if readme.exists():
        return
    readme.write_text(
        f"# {project.name}\n\n{project.description or 'TODO: describe this project.'}\n\n"
        "<!-- Stub generated by Jarvis OS — replace with a real description. -->\n"
    )
    report.note("generated README.md stub (please edit)")
    report.warn("README.md was missing — a stub was generated, edit it")


def ensure_operation_md(project: ProjectSpec, report: BootstrapReport) -> None:
    """Generate/refresh OPERATION.md, preserving the 'Project specifics' section."""
    op_path = project.path / "OPERATION.md"
    specifics = "_None yet._"
    if op_path.exists():
        current = op_path.read_text()
        if f"template v{TEMPLATE_VERSION}" in current.split("\n", 1)[0]:
            report.note("OPERATION.md already at current template version")
            return
        marker = "## Project specifics"
        if marker in current:
            specifics = current.split(marker, 1)[1].strip() or specifics
    template = (ASSETS / "OPERATION.md.tmpl").read_text()
    op_path.write_text(
        template.format(
            template_version=TEMPLATE_VERSION,
            project_name=project.name,
            project_specifics=specifics,
        )
    )
    report.note("wrote OPERATION.md")


def ensure_state_dir(project: ProjectSpec, report: BootstrapReport) -> None:
    state = project.path / ".jarvis"
    if not state.exists():
        state.mkdir()
        report.note("created .jarvis/ state dir")


def bootstrap_project(project: ProjectSpec, force_config: bool = False,
                      dry_run: bool = False) -> BootstrapReport:
    report = BootstrapReport(project=project.name)
    if not project.path.is_dir():
        report.warn(f"path does not exist: {project.path}")
        return report
    if not (project.path / ".git").exists():
        report.warn(f"not a git repository: {project.path} — run `git init` there first")
        return report
    if dry_run:
        report.note("(dry run — no changes written)")
        readme = project.path / "README.md"
        if not readme.exists():
            report.note("would generate README.md stub")
        report.note("would write OPERATION.md, .jarvis/, .gitignore entry, settings.json")
        return report
    ensure_readme(project, report)
    ensure_operation_md(project, report)
    ensure_state_dir(project, report)
    ensure_gitignore(project, report)
    inject_settings(project, report, force=force_config)
    return report
